---
title: "Write functions"
format: html
---
# Instructions

This week, you learned how to write and apply your own functions.

You'll use these skills to classify GFR values into kidney disease stages.

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-renal-treatment/assets/mdrd_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Write functions

In this milestone, you'll create a new variable that classifies the stage of kidney disease for each observation based on the GFR value.

## Recreation

### Part 1 - Import

Before you begin, you will need to import your data set.
Use the code chunk below to read the data from the data file `mdrd.csv`, which is stored in the `data/` folder in your working directory.
Be sure to save the data set to a variable named `mdrd`.

```{python}
#| label: 'recreation_import'

```

### Part 2 - Write a function

Your task is to write a function named `classify_stage()` that will accept a value of `gfr` and return a value between 1 and 5 according to the following information:

- `1` if `gfr` is greater than or equal to 90
- `2` if `gfr` is greater than or equal to 60 (and less than 90)
- `3` if `gfr` is greater than or equal to 30 (and less than 60)
- `4` if `gfr` is greater than or equal to 15 (and less than 30)
- `5` if `gfr` is less than 15

```{python}
#| label: 'recreation-function'


```

Run the following code chunk to test your function on a few different values:

```{python}
#| label: 'compare_results'

classify_stage(40) # should return 3
classify_stage(60) # should return 2
classify_stage(10) # should return 5
```

### Part 3 - Apply

Run the code below to see a table.

```{python}
#| label: 'recreate-this'
#| message: false

solution = pd.read_csv('data/milestone03.csv')
solution
```

Your task is to create this table. Using your function, add a new column to `mdrd` called `kidney_stage` that contains the classified values.

```{python}
#| label: 'recreation_apply'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
mdrd.reset_index(drop=True).round(10).compare(solution.round(10))
```

## Extension

Use the code chunk(s) below to extend your work. Try something that you can learn from experimentation, a help page, or a package website. Some ideas:

1. Which stage(s) of kidney disease are most common in this sample?
2. How many patients in this sample progress through different stages of kidney disease over the course of the study? Do all patients who progress through different stages demonstrate improved kidney function over time? Are there any patients that get worse?
3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Write a function to perform a calculation or recode a variable in your data set
3. Use your updated data set to create at least one graph and/or table

```{python}
#| label: 'extension'

```
