---
title: "Summarize data"
format: html
---
# Instructions

This week, you learned about several more pandas methods.

In this milestone, you'll group the data by patient and then summarize the results to calculate the slope of GFR for each patient.

To learn more about the variables contained in the data set,
refer to the data dictionary [here](https://rstudio.github.io/academy-python-renal-treatment/assets/mdrd_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'})
```

## Summarize data

In this milestone, you'll use groupwise summaries to calculate the slope of GFR for each patient.

## Recreation

### Part 1 - Import

Before you begin, you will need to import the `mdrd` data set. We will use the version from last week's milestone, with the added `kidney_stage` column. Use the code chunk below to read the data from the data file `mdrd_with_stages.csv`, which is stored in the `data/` folder in your working directory.

Be sure to save the data set to a variable named `mdrd`.

```{python}
#| label: 'recreation-import'

```

### Part 2 - Slope function

This week, we'd like to analyze the change in GFR (glomerular filtration rate) over time for each patient in the MDRD study. Specifically, we'll calculate a `gfr_slope` variable like we did in Milestone 2, which is computed as follows for each patient:

> (last GFR - first GFR) / time elapsed

Your task is to write a function called `calc_slope()` that accepts a DataFrame with data for a single patient and calculates the slope of GFR.

_Hint_: `.iloc[0]` will return the first row of a DataFrame, and `.iloc[-1]` will return the last row.

```{python}
#| label: 'recreation-slope'

```

Run the code chunk below to test your function on subsets for a few different patients.

```{python}
#| label: 'compare_results'

calc_slope(mdrd.loc[mdrd['ptid'] == 1]) # should return -0.3922991071428571
calc_slope(mdrd.loc[mdrd['ptid'] == 2]) # should return 0.19829102789645642
calc_slope(mdrd.loc[mdrd['ptid'] == 3]) # should return -0.31563731931668865
```

### Part 3 - Summarize data

Now, you'll use your function to calculate the slope of GFR for each patient.

```{python}
#| label: 'recreate-this'
solution = pd.read_csv('data/milestone04.csv')
solution
```

Your task is to use what you've learned about functions and grouped summaries to transform `mdrd` into this table.

You will need to:

1. Group the data
2. Calculate the slope of GFR for each group
3. Reset the index
4. Rename the new column of data to `gfr_slope`

Work in the code chunk below. Save the result as `patient_summary`. We will use the result in Part 4.

*Note:* You can ignore any warning message you might see caused by dividing by zero (`invalid value encountered in scalar divide`).

```{python}
#| label: 'recreation-summary'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
patient_summary.reset_index(drop=True).round(10).compare(solution.round(10))
```

### Part 4 - Visualize it

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone04.png` to open an image in the Editor pane

Finally, use the new `patient_summary` data to recreate this plot.

```{python}
#| label: 'recreation-visualize'

```

## Extension

Using the code chunk below, investigate a research question about this data. Some ideas:

1. Group by both kidney stage and patient id. How does GFR slope compare across kidney stages?
2. Do you think a patient's current stage of kidney disease would be a useful way to predict the change in GFR over time (`gfr_slope`)?
3. Visualize the data in a new way.
4. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data.
2. Group your data set and apply a calculation to each group.
3. Produce a visualization to compare the results by group.

```{python}
#| label: 'extension'

```
