---
title: "Wrangle rows and columns"
format: html
---
# Instructions

This week, you learned about several more pandas methods and attributes. These functions help you work with the columns in your data set.

You'll use these skills to analyze the trend in GFR for a patient over time.

To learn more about the variables contained in the data set, refer to the data dictionary [here](https://rstudio.github.io/academy-python-renal-treatment/assets/mdrd_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Wrangle rows and columns

In this milestone, you'll visualize the slope of GFR for one patient and then calculate the value of the slope. The slope of GFR tells us the rate of decline in kidney function over time and is what we will use to evaluate the effectiveness of treatments in later milestones.

## Recreation

### Part 1 - Import

Before you begin, you will need to import your data set. Use the code chunk below to read the data from the data file `mdrd.csv`, which is stored in the `data/` folder in your working directory. Be sure to save the data set to a variable named `mdrd`.

```{python}
#| label: 'recreation-import'

```

### Part 2 - Create

Run the code below to see a table.

```{python}
#| label: 'recreate-this'
#| message: false

solution = pd.read_csv('data/milestone02a.csv')
solution
```

Your task is to use what you've learned to transform `mdrd` into this table. You will need to:

1. Subset `mdrd` for records where the `ptid` is 1 then save the result as a new data set named `subset`. Continue to work with `subset`.

2. Select the `ptid`, `gfr` and `months` columns.

Work in the code chunk below.

```{python}
#| label: 'recreation-create'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
subset.reset_index(drop=True).round(10).compare(solution.round(10))
```

### Part 3 - Visualize

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone02.png` to open an image in the Editor pane

Now let's visualize the change in GFR over time for that patient. Your task is to recreate this plot using `subset`.

```{python}
#| label: 'recreation_visualize_1'

# Remember to import the plotnine functions that you'll be using.
# You can add them to the `setup` chunk at the top to keep your code organized.

```

### Part 4 - Calculate

Now you will use `subset` to calculate the average slope of GFR for one individual according to the following equation:

  > (last GFR - first GFR) / time elapsed

Save the results to a variable called `gfr_slope`.
_Hint_: Use `.iloc[0]` to return the first row of a DataFrame and `.iloc[-1]` to return the last row.

```{python}
#| label: 'recreation-calc'

```

Compare your answers to the values in the following variable to check your solution:

```{python}
#| label: 'recreate-this-2'
#| message: false

pd.read_csv('data/milestone02b.csv')
```

## Extension

Using the code chunk below, investigate a research question about this data, using the additional data wrangling skills you learned this week. Some ideas:

1. Calculate and visualize the slope for multiple patients. How do the values compare?
2. Explore other variables in the data. For example, is the amount of protein consumed by each individual consistent across their treatment?
3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Create at least one new variable in your data set using mathematical operations
3. Use your updated data set to create at least one graph and/or table

```{python}
#| label: 'extension'

```
